(function () {
    'use strict';

    var THEMES = [
        { id: 'agatha-christie', name: 'Agatha Christie', emoji: '🏚️', desc: 'Manoir victorien', category: 'classic' },
        { id: 'sherlock-holmes', name: 'Sherlock Holmes', emoji: '🔍', desc: 'Londres 19e siècle', category: 'classic' },
        { id: 'cyberpunk', name: 'Cyberpunk', emoji: '🌃', desc: 'Dystopie néon', category: 'scifi' },
        { id: 'heroic-fantasy', name: 'Heroic Fantasy', emoji: '⚔️', desc: 'Donjons & Magie', category: 'scifi' },
        { id: 'sci-fi', name: 'Sci-Fi', emoji: '👽', desc: 'Space Opera', category: 'scifi' },
        { id: 'lovecraftian', name: 'Horreur Lovecraftienne', emoji: '🐙', desc: 'Paranormal', category: 'horror' },
        { id: 'antiquite', name: 'Antiquité', emoji: '🏛️', desc: 'Péplum', category: 'horror' },
        { id: 'film-noir', name: 'Film Noir', emoji: '🎩', desc: 'Noir des années 40', category: 'classic' },
    ];

    var ASSETS_BASE = 'assets/image true detective/';

    var THEME_ASSETS = {
        'agatha-christie': {
            universe: ASSETS_BASE + 'classic/laboratoire.png',
            crimeScene: ASSETS_BASE + 'classic/scene de crime manoir.png',
            detective: ASSETS_BASE + 'classic/detective-partenaire.png',
            femmeFatale: ASSETS_BASE + 'classic/femme-fatal.png',
            seducteur: ASSETS_BASE + 'classic/le-seducteur.png',
            suspect: ASSETS_BASE + 'classic/Le-suspect.png',
            marginal: ASSETS_BASE + 'classic/Le-marginal.png',
            residence: ASSETS_BASE + 'classic/interieur manoir.png',
            alley: ASSETS_BASE + 'classic/ruelle.png',
            publicPlace: ASSETS_BASE + 'classic/exterieur quartier général.png',
            secretPlace: ASSETS_BASE + 'classic/Le-Lieu-Clandestin-La-Cachette.png',
            laboratory: ASSETS_BASE + 'classic/laboratoire.png',
            headquarters: ASSETS_BASE + 'classic/quartier general.png',
            music: 'sherlock.mp3',
        },
        'sherlock-holmes': {
            universe: ASSETS_BASE + 'classic/laboratoire.png',
            crimeScene: ASSETS_BASE + 'classic/scene de crime manoir.png',
            detective: ASSETS_BASE + 'classic/detective-partenaire.png',
            femmeFatale: ASSETS_BASE + 'classic/femme-fatal.png',
            seducteur: ASSETS_BASE + 'classic/le-seducteur.png',
            suspect: ASSETS_BASE + 'classic/Le-suspect.png',
            marginal: ASSETS_BASE + 'classic/Le-marginal.png',
            residence: ASSETS_BASE + 'classic/interieur manoir.png',
            alley: ASSETS_BASE + 'classic/ruelle.png',
            publicPlace: ASSETS_BASE + 'classic/exterieur quartier général.png',
            secretPlace: ASSETS_BASE + 'classic/Le-Lieu-Clandestin-La-Cachette.png',
            laboratory: ASSETS_BASE + 'classic/laboratoire.png',
            headquarters: ASSETS_BASE + 'classic/quartier general.png',
            music: 'sherlock.mp3',
        },
        'cyberpunk': {
            universe: ASSETS_BASE + 'classic/laboratoire.png',
            crimeScene: ASSETS_BASE + 'classic/scene de crime manoir.png',
            detective: ASSETS_BASE + 'classic/detective-partenaire.png',
            femmeFatale: ASSETS_BASE + 'classic/femme-fatal.png',
            seducteur: ASSETS_BASE + 'classic/le-seducteur.png',
            suspect: ASSETS_BASE + 'classic/Le-suspect.png',
            marginal: ASSETS_BASE + 'classic/Le-marginal.png',
            residence: ASSETS_BASE + 'classic/interieur manoir.png',
            alley: ASSETS_BASE + 'classic/ruelle.png',
            publicPlace: ASSETS_BASE + 'classic/exterieur quartier général.png',
            secretPlace: ASSETS_BASE + 'classic/Le-Lieu-Clandestin-La-Cachette.png',
            laboratory: ASSETS_BASE + 'classic/laboratoire.png',
            headquarters: ASSETS_BASE + 'classic/quartier general.png',
            music: 'cyberpunk.mp3',
        },
        'heroic-fantasy': {
            universe: ASSETS_BASE + 'classic/laboratoire.png',
            crimeScene: ASSETS_BASE + 'classic/scene de crime manoir.png',
            detective: ASSETS_BASE + 'classic/detective-partenaire.png',
            femmeFatale: ASSETS_BASE + 'classic/femme-fatal.png',
            seducteur: ASSETS_BASE + 'classic/le-seducteur.png',
            suspect: ASSETS_BASE + 'classic/Le-suspect.png',
            marginal: ASSETS_BASE + 'classic/Le-marginal.png',
            residence: ASSETS_BASE + 'classic/interieur manoir.png',
            alley: ASSETS_BASE + 'classic/ruelle.png',
            publicPlace: ASSETS_BASE + 'classic/exterieur quartier général.png',
            secretPlace: ASSETS_BASE + 'classic/Le-Lieu-Clandestin-La-Cachette.png',
            laboratory: ASSETS_BASE + 'classic/laboratoire.png',
            headquarters: ASSETS_BASE + 'classic/quartier general.png',
            music: 'heroic fantasy.mp3',
        },
        'sci-fi': {
            universe: ASSETS_BASE + 'classic/laboratoire.png',
            crimeScene: ASSETS_BASE + 'classic/scene de crime manoir.png',
            detective: ASSETS_BASE + 'classic/detective-partenaire.png',
            femmeFatale: ASSETS_BASE + 'classic/femme-fatal.png',
            seducteur: ASSETS_BASE + 'classic/le-seducteur.png',
            suspect: ASSETS_BASE + 'classic/Le-suspect.png',
            marginal: ASSETS_BASE + 'classic/Le-marginal.png',
            residence: ASSETS_BASE + 'classic/interieur manoir.png',
            alley: ASSETS_BASE + 'classic/ruelle.png',
            publicPlace: ASSETS_BASE + 'classic/exterieur quartier général.png',
            secretPlace: ASSETS_BASE + 'classic/Le-Lieu-Clandestin-La-Cachette.png',
            laboratory: ASSETS_BASE + 'classic/laboratoire.png',
            headquarters: ASSETS_BASE + 'classic/quartier general.png',
            music: 'SF.mp3',
        },
        'lovecraftian': {
            universe: ASSETS_BASE + 'classic/laboratoire.png',
            crimeScene: ASSETS_BASE + 'classic/scene de crime manoir.png',
            detective: ASSETS_BASE + 'classic/detective-partenaire.png',
            femmeFatale: ASSETS_BASE + 'classic/femme-fatal.png',
            seducteur: ASSETS_BASE + 'classic/le-seducteur.png',
            suspect: ASSETS_BASE + 'classic/Le-suspect.png',
            marginal: ASSETS_BASE + 'classic/Le-marginal.png',
            residence: ASSETS_BASE + 'classic/interieur manoir.png',
            alley: ASSETS_BASE + 'classic/ruelle.png',
            publicPlace: ASSETS_BASE + 'classic/exterieur quartier général.png',
            secretPlace: ASSETS_BASE + 'classic/Le-Lieu-Clandestin-La-Cachette.png',
            laboratory: ASSETS_BASE + 'classic/laboratoire.png',
            headquarters: ASSETS_BASE + 'classic/quartier general.png',
            music: 'peur.mp3',
        },
        'antiquite': {
            universe: ASSETS_BASE + 'classic/laboratoire.png',
            crimeScene: ASSETS_BASE + 'classic/scene de crime manoir.png',
            detective: ASSETS_BASE + 'classic/detective-partenaire.png',
            femmeFatale: ASSETS_BASE + 'classic/femme-fatal.png',
            seducteur: ASSETS_BASE + 'classic/le-seducteur.png',
            suspect: ASSETS_BASE + 'classic/Le-suspect.png',
            marginal: ASSETS_BASE + 'classic/Le-marginal.png',
            residence: ASSETS_BASE + 'classic/interieur manoir.png',
            alley: ASSETS_BASE + 'classic/ruelle.png',
            publicPlace: ASSETS_BASE + 'classic/exterieur quartier général.png',
            secretPlace: ASSETS_BASE + 'classic/Le-Lieu-Clandestin-La-Cachette.png',
            laboratory: ASSETS_BASE + 'classic/laboratoire.png',
            headquarters: ASSETS_BASE + 'classic/quartier general.png',
            music: 'gaginator.mp3',
        },
        'film-noir': {
            universe: ASSETS_BASE + 'classic/laboratoire.png',
            crimeScene: ASSETS_BASE + 'classic/scene de crime manoir.png',
            detective: ASSETS_BASE + 'classic/detective-partenaire.png',
            femmeFatale: ASSETS_BASE + 'classic/femme-fatal.png',
            seducteur: ASSETS_BASE + 'classic/le-seducteur.png',
            suspect: ASSETS_BASE + 'classic/Le-suspect.png',
            marginal: ASSETS_BASE + 'classic/Le-marginal.png',
            residence: ASSETS_BASE + 'classic/interieur manoir.png',
            alley: ASSETS_BASE + 'classic/ruelle.png',
            publicPlace: ASSETS_BASE + 'classic/exterieur quartier général.png',
            secretPlace: ASSETS_BASE + 'classic/Le-Lieu-Clandestin-La-Cachette.png',
            laboratory: ASSETS_BASE + 'classic/laboratoire.png',
            headquarters: ASSETS_BASE + 'classic/quartier general.png',
            music: 'noire.mp3',
        },
    };

    var TEXTS = {
        en: {
            selectTheme: 'Select your investigation theme to begin',
            startGame: 'Start Investigation',
            resume: 'Resume Investigation',
            caseClosed: 'Case Closed',
            culprit: 'Culprit',
            motive: 'Motive',
            method: 'Method',
            theTruth: 'The Truth',
            newInvestigation: 'New Investigation',
            backToHub: 'Back to Hub',
            generatingInvestigation: 'Generating investigation...',
            loadingScene: 'Preparing the scene...',
            discoveredClues: 'Discovered Clues',
            investigationSteps: 'Investigation Steps',
            noClues: 'No clues discovered yet. Keep investigating!',
            noSteps: 'No investigation steps recorded yet.',
            act: 'Act',
            scene: 'Scene',
            clues: 'Clues',
            skip: 'Skip',
            continue: 'Continue',
            nextPage: 'Next Page',
            talkToNPC: 'Ask a question',
            send: 'Send',
            questionPlaceholder: 'Ask the NPC something...',
            backToChoices: 'Back to choices',
            endConversation: 'End conversation',
            language: 'Language',
            english: 'English',
            french: 'Français',
             gameOver: 'Investigation Complete',
            resumeGame: 'Resume Investigation',
            noSavedGame: 'No saved investigation found',
            puzzlePlaceholder: 'Enter your answer...',
            submit: 'Submit',
            puzzleSolved: 'Correct! The puzzle is solved.',
            puzzleWrong: 'That doesn\'t seem right. Try again.',
            puzzleCorrect: 'Correct answer',
            you: 'You',
            narrator: 'Narrator',
            objective: 'Objective',
            dialogueHistory: 'Dialogue History',
            musicInfo: 'Music',
            sceneType: {
                investigation: 'Investigation',
                interrogation: 'Interrogation',
                puzzle: 'Puzzle',
                tension: 'Tension',
                revelation: 'Revelation',
                credits: 'Credits',
            },
        },
    };

    // Rest of the file continues...
})();