/* =====================================================================
   TRUE DETECTIVE - PHASES & DIALOGUES (contenu narratif V3)
   Structure : 9 phases de 3 pages chacune.

   RÈGLE GÉNÉRALE - LIEUX DES PERSONNAGES (hors besoin du scénario) :
   - Scientifique (Whitmore)        → laboratoire
   - Femme fatale (Lady Vivienne)   → intérieur manoir de la victime
   - Protecteur (Major Hale)        → intérieur manoir de la victime
   - Détective partenaire           → quartier général (QG)
                                      Exception : intro + acte 1,
                                      il est dans le manoir de la victime.
   - Séducteur (Julian Pembrooke)   → intérieur bar
   - Marginal (Silas Crane)         → appartement pauvre (ruelle en narration si scénario l'exige)
   - Suspect (Rupert Blackwood)     → appartement du suspect
   - Criminel (Victor Krane)        → extérieur bar ou ruelle
===================================================================== */
(function (global) {
    'use strict';
    var PHASES = [];

    /* ===== INTRO - Phase 1A : OUVERTURE ===== */
    PHASES.push({
        id: 'intro-1',
        label: { fr: 'Prologue', en: 'Prologue' },
        act: 'Intro',
        type: 'narration',
        music: 'theme',
        pages: [
            { decor: 'universeSherlock', text: { fr: "La ville ne s'endort jamais. Elle halète sous la pluie, comme une bête trop vieille pour mourir. Les réverbères crachent leurs halos jaunes sur les pavés gras, les fiacres glissent sans un bruit, et dans les ruelles, les ombres sont plus longues que les visages. Une cité qui ne pardonne pas l'erreur, qui ne reconnaît que le sang et le silence. Ce soir, elle vous attend.", en: "The city never sleeps. It pants under the rain, like a beast too old to die. Streetlamps spit their yellow halos onto greasy cobblestones, cabs glide without a sound, and in the alleys, shadows are longer than faces. A city that does not forgive mistakes, that recognizes only blood and silence. Tonight, it waits for you." } },
            { decor: 'universe', text: { fr: "La ville murmure, mais elle ment. Dans un appartement cossu, au-dessus des toits, un magnat de l'immobilier a été retrouvé sans vie. On vous a confié l'enquête : la plus délicate, la plus sale, de votre carrière. Ce ne sera pas une partie de whist.", en: "The city whispers, but it lies. In a lavish flat, above the rooftops, a real-estate magnate was found dead. You have been assigned the case: the most delicate, the dirtiest, of your career. This won't be a game of whist." } },
            { decor: 'crimeScene', text: { fr: "Vous poussez la porte. L'air est lourd, sucré, métallique. Le sang a séché sur le parquet en longs filaments bruns. Le coffre-fort est béant, vidé de ses secrets. Sur une table, une montre de poche brisée, son aiguille figée dans un ultime sursaut. Personne ne sait quand le magnat est mort : aucune heure n'est établie. C'est à vous de la trouver. Elle seule peut dire qui ment.", en: "You push the door. The air is heavy, sweet, metallic. Blood has dried on the floor in long brown filaments. The safe gapes open, emptied of its secrets. On a table, a broken pocket watch, its hand frozen in a final jerk. No one knows when the magnat died: no time of death is established. Finding it is your job. It alone can say who lies." } },
            { decor: 'crimeScene', npc: 'detective-partner', text: { fr: "Votre partenaire vous rejoint, l'air grave, le col de son imperméable relevé contre l'humidité : « La victime, Aldric Thorne, n'avait qu'un seul domestique : son garde du corps, le Major Hale. C'est lui qui a découvert le corps. »\n\nWexford s'accroupit près du bureau, examine les taches par terre.\n\n« L'affaire commence ici. Et elle ne sent pas bon. »", en: "Your partner joins you, looking grave, his coat collar turned up against the damp: \"The victim, Aldric Thorne, had one servant: his bodyguard, Major Hale. He found the body.\"\n\nWexford crouches by the desk, examines the stains on the floor.\n\n\"The case begins here. And it doesn't smell good.\"" } }
        ]
    });

    /* ===== INTRO - Phase 1B : FOUILLE DE LA SCÈNE ===== */
    PHASES.push({
        id: 'intro-2',
        label: { fr: 'Recherche', en: 'Investigation' },
        act: 'Intro',
        type: 'dialogue',
        music: 'recherche',
        pages: [
            { decor: 'crimeScene', npc: 'detective-partner', text: { fr: "Le manoir est plongé dans une pénombre épaisse, comme si la maison elle-même retenait son souffle. Les rideaux tirés ne laissent passer que des rais de lumière blafarde. Wexford allume une torche et balaie la pièce du regard, les ombres dansant derrière lui.\n\n« Chaque détail compte. Même celui qui ne dit rien. Je reste là si vous avez besoin. »", en: "The manor is plunged in thick half-light, as if the house itself were holding its breath. The drawn curtains let through only wan rays of light. Wexford switches on a torch and sweeps the room, shadows dancing behind him.\n\n\"Every detail counts. Even the one that says nothing. I'll be here if you need me.\"" } },
            { decor: 'crimeScene',
              text: { fr: "Votre partenaire vous tend la loupe avec un geste las. « Fouillez chaque recoin. Les pièces à conviction vous diront tout - à condition de savoir les lire. »", en: "Your partner hands you the magnifying glass with a weary gesture. 'Search every corner. The evidence pieces will tell you everything - provided you know how to read them.'" },
            minigame: { type: 'scene_fouille', wide: true, evidence: 'forensic',
            title: { fr: "Fouille de la scène", en: "Scene search" },
            desc: { fr: "Explorez la scène à la loupe. Chaque pièce à conviction ouvre une fenêtre détaillée : examinez-les toutes pour reconstituer les circonstances du crime.", en: "Explore the scene with the magnifier. Each piece of evidence opens a detailed window: examine them all to reconstruct how the crime unfolded." },
            clue: { fr: 'Une dette colossale soulignee trois fois, une chevaliere au bord du verre, une menace cachetee aux armes de Blackwood et un recu V.K. au dos signe Rupert. Le vol masquait un creancier qui faisait payer son du par le sang.', en: 'A colossal debt underlined three times, a signet ring on the glass rim, a wax-sealed threat bearing Blackwood\'s crest and a V.K. receipt signed Rupert on the back. The robbery masked a creditor collecting his due in blood.' },
            time: 60,
            sceneImage: null,
            hotspots: [
                    { label: '1', info: { fr: 'Cachet intact, bureau non force : quelqu un de confiance a ouvert. Mais les comptes revelent que ce proche etait un debiteur accule.', en: 'Seal intact, desk unforced : someone trusted opened. But the accounts show this close one was a cornered debtor.' } },
                    { label: '2', info: { fr: 'La carafe renversee et un verre au bord marque de la trace d une chevaliere - le sceau de Rupert Blackwood. Il est venu avant.', en: 'The overturned decanter and a rim glass marked by a signet ring - Rupert Blackwood\'s crest. He came before.' } },
                    { label: '3', info: { fr: 'Le livre de comptes : la colonne Rupert Blackwood montre une dette enorme, soulignee trois fois, puis une note : a regler avant la fin du mois.', en: 'The ledger : the "Rupert Blackwood" column shows a huge debt, underlined three times, then a note : due before month\'s end.' } },
                    { label: 'A', info: { fr: 'Une lettre de menace adressee a mon debiteur le plus cher - arrachee en partie, mais le cachet de cire aux armes de Blackwood est reconnaissable.', en: 'A threat letter addressed to my dearest debtor - partly torn, but Blackwood\'s wax crest is recognizable.' } },
                    { label: 'C', info: { fr: 'L encrier intact et la plume seche depuis des heures : l ultime echange de mots eu lieu bien AVANT, a voix basse, autour d une table.', en: 'The inkwell untouched and the pen dry for hours : the last exchange of words happened long BEFORE, whispered, around a table.' } },
                    { label: '4', info: { fr: 'Le fauteuil renverse et une montre de poche au sol : la victime a recu un visiteur de nuit, a l heure ou l on ne recoit que les creanciers.', en: 'The overturned chair and a pocket watch on the floor : the victim received a night visitor, at the hour one only receives creditors.' } },
                    { label: '5', info: { fr: 'La mare de sang face au bureau : frappe par surprise au milieu d une ultime conversation d argent. Pas de lutte - on a frappe debout.', en: 'The pool of blood facing the desk : struck by surprise in a final money conversation. No struggle - struck standing.' } },
                    { label: '6', info: { fr: 'Un recu V.K. plie : une forte somme versee pour services - et au dos, l ecriture de l obligataire : Rupert.', en: 'A folded V.K. receipt : a large sum paid for services - and on the back, the debtor\'s handwriting : Rupert.' } }
                ] } },
            { decor: 'crimeScene', npc: 'detective-partner', text: { fr: "Le carnet déchiré révèle des pages manquantes, comme si on avait cherché à effacer une partie de l'histoire. En les reconstituant, vous découvrez des versements réguliers à un certain « V.K. » - des sommes qui ne figurent dans aucune comptabilité officielle.", en: "The torn ledger reveals missing pages, as if someone had tried to erase part of the story. By reassembling them, you discover regular payments to a certain \"V.K.\" - sums that appear in no official accounting." } },
            { decor: 'crimeScene', npc: 'detective-partner', text: { fr: "Votre partenaire vous observe, les mains dans les poches : « Vous tenez quelque chose ? Ces indices dessinent un mobile. Continuons. »", en: "Your partner watches you, hands in pockets: \"Are you onto something? These clues are forming a motive. Let's continue.\"" } }
        ]
    });

    /* ===== ACTE 1 - Phase 1 : INTERROGATOIRES AU MANOIR ===== */
    PHASES.push({
        id: 'act1_1',
        label: { fr: 'Interrogatoires', en: 'Interrogations' },
        act: 'Acte 1',
        type: 'dialogue',
        music: 'recherche',
        pages: [
            { decor: 'residence', npc: 'protecteur', interrogation: 'protecteur', text: { fr: "Le Major Hale vous accueille dans le salon du manoir. Son uniforme est impeccable, mais une goutte de sueur perle à sa tempe. Il se tient droit, les mains croisées derrière le dos, comme s'il s'exerçait à ne pas trembler.\n\n« Je vous ai attendu, inspecteur. La maison est en deuil, faites vite. »\n\nVous sentez un mélange d'arrogance et de contrôle. Hale se maîtrise, mais ses yeux vous fuient. Choisissez votre angle d'attaque.", en: "Major Hale greets you in the manor lounge. His uniform is impeccable, but a drop of sweat beads at his temple. He stands straight, hands clasped behind his back, as if practicing not to tremble.\n\n\"I've been expecting you, inspector. The house is in mourning, make it quick.\"\n\nYou sense a mix of arrogance and control. Hale keeps his composure, but his eyes avoid yours. Pick your angle of attack." } },
            { decor: 'residence', npc: 'femme-fatale', interrogation: 'femme-fatale', text: { fr: "Lady Vivienne vous reçoit dans le boudoir aux rideaux de velours rouge. Elle ne se lève pas. Une tasse de thé fume entre ses doigts gantés, mais elle n'y porte pas les lèvres.\n\n« Mon mari avait des ennemis, certes. Mais l'auteur de ce crime… c'est quelqu'un de la maison. Quelqu'un qui connaissait ses habitudes. »\n\nElle vous défie du regard, les yeux deux charbons dans la pénombre. Lady Vivienne attend votre première question.", en: "Lady Vivienne receives you in the boudoir with blood-red velvet curtains. She does not rise. A teacup smokes between her gloved fingers, but she does not raise it to her lips.\n\n\"My husband had enemies, certainly. But the perpetrator… it's someone from the house. Someone who knew his habits.\"\n\nShe challenges you with her gaze, eyes like coals in the half-light. Lady Vivienne waits for your first question." } },
            { decor: 'residence', npc: 'detective-partner', text: { fr: "La montre du Duc gît sur la table du salon, brisée. « Elle a dû valser dans la bagarre, soupire Wexford en se penchant. Voyez ce qu'elle peut encore nous apprendre. »", en: "The Duke's watch lies on the lounge table, broken. \"It must have flown off in the struggle,\" Wexford sighs, leaning in. \"See what it can still tell us.\"" } },
            { decor: 'residence', text: { fr: "La montre du Duc gît sur la table, brisée. L'aiguille figée indique l'heure. Existe-t-il un code caché dans cette montre ?", en: "The Duke's watch lies on the table, broken. The frozen hand shows the time. Is there a hidden code in this watch?" }, minigame: { type: 'montre_code', time: 45, code: [1, 9, 8, 1], title: { fr: "La Montre du Duc", en: "The Duke's Watch" }, desc: { fr: "Examinez la montre pour trouver l'heure du crime et un code secret.", en: "Examine the watch to find the time of death and a secret code." }, clue: { fr: 'INDICE MINEUR : 1981 (coffre). INDICE MAJEUR : 22h09 - Rupert, qui pretend etre parti a 21h30, a eu tout le temps de revenir.', en: 'MINOR : 1981 (safe). MAJOR : 10:09pm - Rupert, who claims he left at 9:30pm, had plenty of time to return.' }, sceneImage: null }},
            { decor: 'residence', npc: 'detective-partner', text: { fr: "Après examen : « Bien. Maintenant, qui interroger en premier ? Blackwood, le notaire ? Ou ce témoin dans la ruelle ? Pembrooke, l'ami, est sans doute au bar. »", en: "After examination: \"Good. Now, who should we question first? Blackwood, the notary? Or the witness in the alley? Pembrooke, the friend, is probably at the bar.\"" } },
            { decor: 'headquarters', npc: 'detective-partner', text: { fr: "Votre partenaire fait le point, le doigt tapotant le bord du tableau : « On a deux versions qui ne tiennent pas ensemble. Hale dit être en panne avec Pembrooke, mais Vivienne assure être seule au manoir. L'un d'eux ment. À vous de voir qui. »", en: "Your partner takes stock, finger tapping the edge of the board: \"We have two versions that don't hold together. Hale says he was broken down with Pembrooke, but Vivienne claims she was alone at the manor. One of them is lying. It's up to you to see who.\"" } },
            { decor: 'headquarters', text: { fr: "Le réseau d'alibis s'étend devant vous. Chaque carte est une déposition. Identifiez les mensonges.", en: "The alibi network spreads out before you. Each card is a testimony. Identify the lies." }, minigame: { type: 'reseau_alibis', difficulty: 'easy', time: 60, evidence: 'witness', title: { fr: "Le Réseau d'alibis — 2 cartes", en: "The Alibi Network — 2 cards" }, desc: { fr: "Deux dépositions se contredisent déjà. Cliquez sur chaque carte : Mensonge ou Vérité. Identifiez le menteur.", en: "Two testimonies already contradict each other. Click each card : Lie or Truth. Identify the liar." }, clue: { fr: "Le réseau des deux premiers témoins révèle une contradiction : l'un ment sur sa présence sur les lieux.", en: "The network of the first two witnesses reveals a contradiction : one lies about being on scene." }, testimonies: [
                { id: 'hale', witness: { fr: "Major Hale", en: "Major Hale" }, statement: { fr: "J'étais en panne avec Pembrooke à 22h. Le verrou du manoir a été ouvert avec une clé, pas forcé. La victime n'a pas opposé de résistance.", en: "I was broken down with Pembrooke at 10pm. The manor lock was opened with a key, not forced. The victim didn't resist." }, isLie: false },
                { id: 'vivienne', witness: { fr: "Lady Vivienne", en: "Lady Vivienne" }, statement: { fr: "J'étais au théâtre avec des amies, puis seule au manoir. Mon mari et moi avions une relation basée sur l'argent, pas l'amour, je n'avais aucune raison de le tuer.", en: "I was at the theatre with friends, then alone at the manor. My husband and I had a relationship based on money, not love, I had no reason to kill him." }, isLie: true }
            ] }},
            { decor: 'headquarters', npc: 'detective-partner', text: { fr: "Votre partenaire synthétise : « Les contradictions se confirment. Un ou plusieurs témoignages mentent. Continuez l'enquête. » ", en: "Your partner summarizes: \"The contradictions are confirmed. One or more testimonies are lying. Keep investigating.\" " } }
        ]
    });

     /* ===== ACTE 1 - Phase 2 : SORTIE ET PREMIERS TÉMOIGNAGES ===== */
     PHASES.push({
         id: 'act1_2',
         label: { fr: 'Témoignages', en: 'Testimonies' },
         act: 'Acte 1',
         type: 'dialogue',
         music: 'reflexion',
         pages: [
             { decor: 'residence', npc: 'detective-partner', text: { fr: "Avant de partir, vous revoyez vos notes avec Wexford dans le vestibule du manoir. L'odeur de cire et de bougie flotte encore.\n\n« Le clochard de la ruelle a vu quelque chose cette nuit-la. Mais passons d'abord chez Blackwood, le notaire - il gétait les affaires du Duc. Et le clochard, on l'interceptera au retour. »", en: "Before leaving, you review your notes with Wexford in the manor vestibule. The scent of wax and candle still hangs.\n\n\"The homeless man in the alley saw something that night. But let's stop by Blackwood's, the notary - he handled the Duke's affairs. We'll catch the homeless man on the way back.\"" } },
             { decor: 'residence', npc: 'detective-partner', text: { fr: "La chronologie s'assemble dans votre esprit comme les pièces d'un puzzle maudit : Hale prétendait être en panne avec Pembrooke à 22h, mais les indices placent le manoir sur les lieux à 22h09. L'alibi du Major est fissuré. Une fissure suffit pour faire entrer la vérité.", en: "The timeline assembles in your mind like pieces of a cursed puzzle: Hale claimed to be broken down with Pembrooke at 10pm, but clues place the manor on scene at 10:09pm. Hale's alibi is cracked. A crack is all it takes for the truth to enter." } },
             { decor: 'secretPlace', npc: 'suspect', interrogation: 'suspect', text: { fr: "Chez Rupert Blackwood, dans son appartement cossu. Il vous ouvre, l'air nerveux, les yeux fuyants. Blackwood vous défie avec une grille.\n\n« Entrez, inspecteur. Je ne sais pas ce que trafique le Duc ces derniers temps, mais les tensions sur le testament se multiplient. J'ai peur que tout cela finisse mal. »\n\nDerrière son bureau de notaire, il paraît fatigué, mais pas par le chagrin. Il vous fait signe de vous asseoir.", en: "At Rupert Blackwood's place, in his lavish apartment. He opens the door, looking uneasy, eyes darting.\n\n\"Come in, inspector. I don't know what the Duke has been up to lately, but the tensions around the will keep growing. I'm afraid this will end badly.\"\n\nBehind his notary desk, he looks tired, but not from grief. He gestures for you to sit." } },
              { decor: 'alley', npc: 'marginal', interrogation: 'marginal', text: { fr: "Sur le chemin du retour, à la sortie du manoir, dans la ruelle adjacente, Silas Crane grelotte dans un coin. Vous l'abordez doucement. Silas vous propose de construire une tour.\n\n« T'as une pièce, inspecteur ? »\n\nVous lui glissez une monnaie. Il se détend, prêt à parler.", en: "On the way back, at the manor exit, in the adjacent alley, Silas Crane is shivering in a corner. You approach him gently.\n\n\"Got a coin, inspector?\"\n\nYou slip him some change. He relaxes, ready to talk." } },
              { decor: 'headquarters', npc: 'detective-partner', text: { fr: "Votre partenaire fait le point, le doigt tapotant le bord du tableau : « Ces quatre dépositions se répondent et se contredisent. Préparez-vous à analyser le réseau d'alibis. »", en: "Your partner takes stock, finger tapping the edge of the board: \"These four depositions answer and contradict each other. Get ready to analyze the alibi network.\"" } },
             { decor: 'headquarters', text: { fr: "Quatre dépositions à croiser. Le réseau s'épaissit, les mensonges se multiplient.", en: "Four testimonies to cross-reference. The network thickens, the lies multiply." }, minigame: { type: 'reseau_alibis', difficulty: 'medium', time: 90, evidence: 'witness', title: { fr: "Le Réseau d'alibis — 4 cartes", en: "The Alibi Network — 4 cards" }, desc: { fr: "Quatre dépositions. Certaines se contredisent déjà. Cliquez sur chaque carte : Mensonge ou Vérité. Identifiez les menteurs.", en: "Four testimonies. Some already contradict each other. Click each card : Lie or Truth. Identify the liars." }, clue: { fr: "Le réseau des quatre témoins révèle des contradictions : Silas ment sur le rôdeur et Krane nie sa présence. La victime devait de l'argent à Krane et voulait qu'il élimine Pembrooke, mais l'arme a tué le Duc.", en: "The network of the four witnesses reveals contradictions: Silas lies about the prowler and Krane denies his presence. The victim owed money to Krane and wanted him to eliminate Pembrooke, but the weapon killed the Duke instead." }, testimonies: [
                { id: 'vivienne', witness: { fr: "Lady Vivienne", en: "Lady Vivienne" }, statement: { fr: "J'étais au théâtre avec des amies, puis seule au manoir. Mon mari et moi avions une relation basée sur l'argent, pas l'amour, je n'avais aucune raison de le tuer.", en: "I was at the theatre with friends, then alone at the manor. My husband and I had a relationship based on money, not love, I had no reason to kill him." }, isLie: false },
                { id: 'hale', witness: { fr: "Major Hale", en: "Major Hale" }, statement: { fr: "J'étais en panne avec Pembrooke à 22h. Le verrou du manoir a été ouvert avec une clé, pas forcé. La victime n'a pas opposé de résistance.", en: "I was broken down with Pembrooke at 10pm. The manor lock was opened with a key, not forced. The victim didn't resist." }, isLie: false },
                { id: 'silas', witness: { fr: "Silas Crane", en: "Silas Crane" }, statement: { fr: "J'ai vu un rôdeur à 22h près du pavillon, montre en or, nerveux. Et j'ai vu Blackwood passer à 20h, le notaire a toujours été réglo.", en: "I saw a prowler at 10pm near the pavilion, gold watch, nervous. And I saw Blackwood pass at 8pm, the notary has always been straight." }, isLie: true },
                { id: 'krane', witness: { fr: "Victor Krane", en: "Victor Krane" }, statement: { fr: "Pour qui paye. Cette nuit-là, j'étais seul. Les clochards racontent n'importe quoi, surtout ce Silas, un vagabond au passé trouble.", en: "For whoever pays. That night, I was alone. The homeless make up anything, especially that Silas, a vagrant with a murky past." }, isLie: true }
            ] }},
             { decor: 'headquarters', npc: 'detective-partner', text: { fr: "Votre partenaire synthétise : « Les contradictions se confirment. Un ou plusieurs témoignages mentent. Continuez l'enquête. »", en: "Your partner summarizes: \"The contradictions are confirmed. One or more testimonies are lying. Keep investigating.\"" } }
         ]
     });

    /* ===== ACTE 2 - Phase 1 : PISTE DU BAR ===== */
    PHASES.push({
        id: 'act2_1',
        label: { fr: 'Piste du bar', en: 'Bar lead' },
        act: 'Acte 2',
        type: 'dialogue',
        music: 'enigme',
        pages: [
            { decor: 'headquarters', npc: 'detective-partner', text: { fr: "Faisons le point sur les indices. Les versements à V.K. et les empreintes du Major Hale sur la mention V.K. sont notre fil conducteur. Mais il nous manque une clé à quatre chiffres. Allons interroger Pembrooke et Krane au bar, capter leur réaction.", en: "Let's take stock. The payments to V.K. and Major Hale's fingerprints on the V.K. entry are our thread. But we lack a four-digit key. Let's head to the bar and watch Pembrooke and Krane react." } },
            { decor: 'barInterieur', npc: 'seducteur', interrogation: 'seducteur', text: { fr: "A l'intérieur du bar, la fumée stagne sous les néons. Vous vous installez au comptoir, à côté de Julian Pembrooke.\n\n- Monsieur Pembrooke. On vous a vu avec le Duc la veille de sa mort. Le verrou du manoir a été ouvert avec une clé, pas forcé. Comment l'expliquez-vous ?\n\nPembrooke fait tourner son verre sans y porter les lèvres. Il vous regarde par-dessus, un sourire en coin.\n\n- Le Duc m'avait engagé pour... pour autre chose. Je devais le rendre aveugle, pas le tuer. Mais l'arme a mal tourné. Et ce n'était pas la première fois que j'attendais près du pavillon ce soir-là.", en: "Inside the bar, smoke lingers under the neon lights. You sit at the counter, next to Julian Pembrooke.\n\n- Mr. Pembrooke. You were seen with the Duke the day before his death. The manor lock was opened with a key, not forced. How do you explain that ?\n\nPembrooke spins his glass without raising it to his lips. He glances at you from under his brow, a wry smile.\n\n- The Duke had hired me for... for something else. I was supposed to blind him, not kill him. But the weapon misfired. And it wasn't the first time I was waiting near the pavilion that night." } },
            { decor: 'publicPlace', npc: 'criminel', interrogation: 'criminel', text: { fr: "Dehors, sous la lumière crue des réverbères, Victor Krane se tient devant l'entrée du bar, le curedent entre les dents. L'air frais de la nuit lui redonne un peu de nervosité. Krane vous propose de retourner des cartes.\n\n- Monsieur Krane. Le Duc vous doit de l'argent, et vous étiez dans le quartier cette nuit-là. Le verrou du manoir a été ouvert avec une clé. Dites-moi tout.\n\nKrane ricane, mais son regard fuit brièvement.\n\n- Le Duc m'a payé pour un élimination. Pas de vol, pas de viol. Juste une disparition. Mais quelqu'un a tiré avant moi.", en: "Outside, under the harsh light of the streetlamps, Victor Krane stands by the bar entrance, a toothpick between his teeth. The cool night air makes him a little nervous.\n\n- Mr. Krane. The Duke owed you money, and you were in the neighborhood that night. The manor lock was opened with a key. Tell me everything.\n\nKrane snorts, but his gaze darts away briefly.\n\n- The Duke paid me for an elimination. Not a robbery, not a assault. Just a disappearance. But someone fired before I did." } },
            { decor: 'headquarters', npc: 'detective-partner', text: { fr: "De retour au QG, votre partenaire aligne les six dépositions sur le tableau. « Ces témoignages se répondent, parfois mal. Préparez-vous à analyser le réseau complet. »", en: "Back at HQ, your partner lines up the six testimonies on the board. \"These testimonies answer each other, sometimes poorly. Get ready to analyze the full network.\"" } },
            { decor: 'headquarters', text: { fr: "Six témoignages, un réseau complet. Les mensonges s'enchevêtrent. Trouvez le vrai coupable.", en: "Six testimonies, a complete network. The lies intertwine. Find the true culprit." }, minigame: { type: 'reseau_alibis', difficulty: 'hard', time: 90, evidence: 'witness', title: { fr: "Le Réseau d'alibis — 6 cartes", en: "The Alibi Network — 6 cards" }, desc: { fr: "Six dépositions. Toutes se répondent ou se contredisent. Cliquez sur chaque carte : Mensonge ou Vérité. Identifiez les menteurs.", en: "Six testimonies. They all answer or contradict each other. Click each card : Lie or Truth. Identify the liars." }, clue: { fr: "Le réseau complet révèle trois menteurs (Vivienne + Pembrooke + Krane) qui se couvrent mutuellement. Le Duc a engagé Krane pour tuer Pembrooke, mais l'arme a tué le maître.", en: "The complete network reveals three liars (Vivienne + Pembrooke + Krane) who cover for each other. The Duke hired Krane to kill Pembrooke, but the weapon killed the master." }, testimonies: [
                { id: 'hale', witness: { fr: "Major Hale", en: "Major Hale" }, statement: { fr: "J'étais en panne avec Pembrooke à 22h. Le verrou du manoir a été ouvert avec une clé, pas forcé. La victime n'a pas opposé de résistance.", en: "I was broken down with Pembrooke at 10pm. The manor lock was opened with a key, not forced. The victim didn't resist." }, isLie: false },
                { id: 'vivienne', witness: { fr: "Lady Vivienne", en: "Lady Vivienne" }, statement: { fr: "J'étais au théâtre avec des amies, puis seule au manoir. Mon mari et moi avions une relation basée sur l'argent, pas l'amour, je n'avais aucune raison de le tuer.", en: "I was at the theatre with friends, then alone at the manor. My husband and I had a relationship based on money, not love, I had no reason to kill him." }, isLie: true },
                { id: 'pembrooke', witness: { fr: "Julian Pembrooke", en: "Julian Pembrooke" }, statement: { fr: "Ma voiture est tombée en panne, Hale m'a rejoint à 22h. J'étais SEUL à attendre, aucun rôdeur n'est passé près du manoir cette nuit-là.", en: "My car broke down, Hale joined me at 10pm. I was ALONE waiting, no prowler passed near the manor that night." }, isLie: true },
                { id: 'blackwood', witness: { fr: "Rupert Blackwood", en: "Rupert Blackwood" }, statement: { fr: "J'ai dîné avec le Duc à 19h, il voulait retirer des fonds. Je suis parti vers 20h, Silas m'a vu passer au portail. Le testament m'importe peu, c'est l'héritier qui compte.", en: "I dined with the Duke at 7pm, he wanted to withdraw funds. I left around 8pm, Silas saw me pass the gate. The will matters little to me, it's the heir that matters." }, isLie: false },
                { id: 'silas', witness: { fr: "Silas Crane", en: "Silas Crane" }, statement: { fr: "J'ai vu un rôdeur à 22h près du pavillon, montre en or, nerveux. Et j'ai vu Blackwood passer à 20h, le notaire a toujours été réglo.", en: "I saw a prowler at 10pm near the pavilion, gold watch, nervous. And I saw Blackwood pass at 8pm, the notary has always been straight." }, isLie: false },
                { id: 'krane', witness: { fr: "Victor Krane", en: "Victor Krane" }, statement: { fr: "Pour qui paye. Cette nuit-là, j'étais seul. Les clochards racontent n'importe quoi, surtout ce Silas, un vagabond au passé trouble.", en: "For whoever pays. That night, I was alone. The homeless make up anything, especially that Silas, a vagrant with a murky past." }, isLie: true }
            ] }},
            { decor: 'headquarters', npc: 'detective-partner', text: { fr: "Votre partenaire synthétise : « Le réseau révèle des failles majeures. Deux alibis de panne se recouvrent, une liaison est cachée, et Krane a été engagé par le Duc pour éliminer Pembrooke, mais l'arme a tué le maître. » ", en: "Your partner summarizes: \"The network reveals major flaws. Two breakdown alibis overlap, an affair is hidden, and Krane was hired by the Duke to eliminate Pembrooke, but the weapon killed the master.\" " } }
        ]
    });

    /* ===== ACTE 2, Phase 2 : LABORATOIRE - L'ADN DE TOUS ===== */
    PHASES.push({
        id: 'act2_2',
        label: { fr: 'Laboratoire', en: 'Laboratory' },
        act: 'Acte 2',
        type: 'dialogue',
        music: 'enigme',
        pages: [
            { decor: 'headquarters', npc: 'detective-partner', text: { fr: "De retour au QG, votre partenaire vérifie les dossiers. « Whitmore a les résultats des tests ADN. Allons-y, c'est décisif. »", en: "Back at HQ, your partner checks the files. \"Whitmore has the DNA test results. Let's go, this is decisive.\"" } },
                        { decor: 'laboratory', npc: 'scientifique', text: { fr: "Au laboratoire, la lumière est stérile et froide. Les grilles d'analyse lumineuses scintillent au-dessus des paillasses. Le docteur Whitmore relève la tête de ses lunettes, le visage grave.\n\n« Inspecteur, les analyses sont sans appel. L'ADN relevé sur l'arme du crime et sur le battant de la porte... ne désigne pas un coupable. Il les désigne tous. Des traces infimes de chaque suspect ont été retrouvées sur les lieux. »\n\nIl pose un dossier épais sur la table.\n\n« La scène a été touchée, manipulée, fréquentée par chacun d'eux. Il va falloir les confronter directement chez eux, dans leurs décors, pour voir comment ils réagissent. Mais avant, ces échantillons d'ADN nécessitent une analyse plus fine dans mes éprouvettes. Prouvez-moi que vous savez isoler chaque composant. »", en: "At the laboratory, the light is sterile and cold. The luminous analysis grids flicker above the benches. Dr. Whitmore looks up from his glasses, his face grave.\n\n\"Inspector, the analyses are conclusive. The DNA found on the murder weapon and on the door frame... does not point to one killer. It points to all of them. Minute traces of each suspect were found at the scene.\"\n\nHe places a thick file on the table.\n\n\"The scene has been touched, manipulated, frequented by every one of them. You will need to confront them directly, in their own surroundings, to see how they react. But first, these DNA samples require a finer analysis in my test tubes. Prove to me you can isolate each component.\"" } },
            { decor: 'laboratory', npc: 'scientifique', minigame: { type: 'chemistry', time: 45, title: { fr: '🧪 Analyse Toxico - Laboratoire', en: '🧪 Tox Analysis - Lab' }, desc: { fr: 'Transvasez les réactifs pour regrouper chaque fluide pur dans son éprouvette.', en: 'Pour reagents to group each pure fluid in its tube.' }, clue: { fr: 'L\'analyse révèle un poison rare des herbiers juridiques, dont seul un homme de loi possédait la connaissance : le profil toxique désigne Rupert Blackwood.', en: 'The analysis reveals a rare poison from legal herbals, knowledge only a man of law possessed: the tox profile points to Rupert Blackwood.' }, evidence: 'forensic' }, text: { fr: "« Prouvez-moi que vous savez isoler chaque composant. » Whitmore vous tend la fiche d'analyse. Les éprouvettes contiennent des réactifs mélangés : il faut transvaser chaque fluide pur dans son éprouvette pour libérer l'ADN toxique.", en: "\"Prove to me you can isolate each component.\" Whitmore hands you the analysis sheet. The test tubes contain mixed reagents: you must pour each pure fluid into its tube to release the toxic DNA." } },
            { decor: 'laboratory', npc: 'detective-partner', text: { fr: "Wexford range les dossiers. « L'ADN confirme que tous ont été présents. Mais tous mentionnent le coffre, et personne ne sait pourquoi leur ADN est sur l'arme. Il est temps de les confronter tous ensemble. »", en: "After analyzing the test tubes, Wexford puts away the files. \"The DNA confirms all were present, but everyone mentions the safe, and no one can explain why their DNA is on the weapon. It's time to confront them all together.\"" } }
        ]
    });
    /* ===== ACTE 2, Phase 3 : INTERROGATOIRES SUR SITE ===== */
    PHASES.push({
        id: 'act2_3',
        label: { fr: 'Interrogatoires', en: 'Interrogations' },
        act: 'Acte 2',
        type: 'dialogue',
        music: 'recherche',
        pages: [
            { decor: 'headquarters', npc: 'detective-partner', text: { fr: "Whitmore tend le dossier ADN. « Toutes ces traces... personne n'est innocent. Mais la scène a été fréquentée par chacun pour des raisons légites. Vous décidez de les confronter un par un, dans leurs lieux. »", en: "Whitmore hands you the DNA file. \"All these traces... no one is innocent. But the scene was frequented by each for legitimate reasons. You decide to confront them one by one, in their own spaces.\"" } },
            { decor: 'residence', npc: 'protecteur', interrogation: 'protecteur', text: { fr: "Au manoir, le Major Hale ajuste ses gants blancs. Vous montrez l'ADN.\n\n« Monsieur le Major. Votre ADN est sur l'arme du crime. Vous étiez garde du corps ? »\n\n« Bien sûr. J'accompagnais le Duc à un examen ce soir-là. Il voulait vérifier la sécurité du manoir. J'ai manié l'arme pour vérifier qu'elle était en ordre. »\n\nIl hésite. « Et le coffre... le Duc gardait des papiers sensibles. Il m'avait dit de protéger l'accès. »", en: "At the manor, Major Hale adjusts his white gloves. You show him the DNA.\n\n\"Major Hale. Your DNA is on the murder weapon. You were the bodyguard?\"\n\n\"Of course. I was accompanying the Duke to an inspection that evening. He wanted to check the manor's security. I handled the weapon to verify it was in order.\"\n\nHe hesitates. \"And the safe... the Duke kept sensitive papers. He told me to protect access to it.\"" } },
            { decor: 'residence', npc: 'femme-fatale', interrogation: 'femme-fatale', text: { fr: "Dans le boudoir, Vivienne feuillette ses ongles.\n\n« Mon ADN ? Le Duc me devait de l'argent. J'étais venue rouvrir la fenêtre, il faisait froid dans le bureau. »\n\nElle sourit. « Ce coffre... le Duc était parano. Il m'a dit qu'il contenait des preuves contre Lady Vivienne. »", en: "In the boudoir, Vivienne examines her nails.\n\n\"My DNA? The Duke owed me money. I came to open the window, it was cold in the office.\"\n\nShe smiles. \"That safe... the Duke was paranoid. He told me it contained evidence against Lady Vivienne.\"" } },
            { decor: 'barInterieur', npc: 'seducteur', interrogation: 'seducteur', text: { fr: "Pembrooke essuie un verre, les mains moites.\n\n« Vous trouvez mon ADN sur la porte ? Le Duc m' devait de la tune. J'étais venu pour un rendez-vous. »\n\nIl baisse les yeux. « Ce coffre... il m'a dit que Lady Vivienne y cachait des preuves de notre liaison. »", en: "Pembrooke wipes a glass, his hands clammy.\n\n\"You find my DNA on the door? The Duke owed me money. I came for a meeting.\"\n\nHe looks down. \"That safe... he told me Lady Vivienne hid proof of our affair in it.\"" } },
            { decor: 'alley', npc: 'marginal', interrogation: 'marginal2', text: { fr: "Silas grelotte dans un coin. Vous lui glissez une pièce.\n\n« Mon ADN ? J'ai reçu l'aumône comme prévu. Le Duc m'a offert un repas chaud, comme toujours. »\n\nIl sourit. « Le coffre... le Duc me disait qu'il y avait quelque chose de compromettant à l'intérieur. »", en: "Silas shivers in a corner. You slip him a coin.\n\n\"My DNA? I received alms as usual. The Duke offered me a warm meal, like always.\"\n\nHe smiles. \"The safe... the Duke told me there was something compromising inside.\"" } },
            { decor: 'secretPlace', npc: 'suspect', interrogation: 'suspect', text: { fr: "Blackwood transpire en ouvrant son dossier.\n\n« Mon ADN ? J'avais rendez-vous avec le Duc ce soir-là pour un acte de fiducie. »\n\nIl se tait. « Le coffre... le Duc m'a dit qu'il contenait des documents que Vivienne attendait. »\n\nSilas, dans la ruelle, a croisé Krane en sortant du bureau du Duc.", en: "Blackwood sweats as he opens his file.\n\n\"My DNA? I had an appointment with the Duke that evening for a trust deed.\"\n\nHe falls silent. \"The safe... the Duke told me it contained documents that Vivienne was waiting for.\"\n\nSilas, in the alley, met Krane leaving the Duke's office." } },
            { decor: 'publicPlace', npc: 'criminel', interrogation: 'criminel', text: { fr: "Krane ricane, le curedent entre les dents.\n\n« Mon ADN sur l'arme ? Le Duc m'avait engagé pour une élimination. »\n\nIl détourne le regard. « Ce soir-là, j'avais un rendez-vous avec le Duc dans son bureau. Mais quelqu'un était déjà entré. »\n\nKrane se rapproche. « Le coffre... le Duc me disait qu'il y avait quelque chose de compromettant à l'intérieur. »", en: "Krane snorts, a toothpick between his teeth.\n\n\"My DNA on the weapon? The Duke hired me for an elimination.\"\n\nHe looks away. \"That evening, I had an appointment with the Duke in his office. But someone was already inside.\"\n\nKrane leans closer. \"The safe... the Duke told me there was something compromising inside.\"" } },
            { decor: 'headquarters', npc: 'detective-partner', text: { fr: "Wexford écoute, puis étale les dépositions. « Chacun a une raison pour être là... mais tous mentionnent le coffre. Et personne ne peut expliquer pourquoi leur ADN est sur l'arme. »", en: "Wexford listens, then lays out the depositions. \"Everyone has a reason to be there... but everyone mentions the safe. And no one can explain why their DNA is on the weapon.\"" } },
            { decor: 'headquarters', text: { fr: "Toutes les dépositions sont sur la table. Le réseau complet révèle la vérité.", en: "All testimonies are on the table. The complete network finally reveals the truth." }, minigame: { type: 'reseau_alibis', difficulty: 'hard', time: 90, evidence: 'witness', title: { fr: "Le Réseau d'alibis — 6 cartes", en: "The Alibi Network — 6 cards" }, desc: { fr: "Six dépositions. Toutes se répondent ou se contredisent. Cliquez sur chaque carte : Mensonge ou Vérité. Identifiez les menteurs.", en: "Six testimonies. They all answer or contradict each other. Click each card : Lie or Truth. Identify the liars." }, clue: { fr: "Le réseau complet révèle que chacun avait une raison légitime d'être au manoir, mais le coffre est la clé. Silas et Krane corroborent leur rencontre. Les autres mentionnent tous le coffre.", en: "The complete network reveals that everyone had a legitimate reason to be at the manor, but the safe is the key. Silas and Krane corroborate their encounter. The others all mention the safe." }, testimonies: [
                { id: 'hale', witness: { fr: "Major Hale", en: "Major Hale" }, statement: { fr: "J'étais en panne avec Pembrooke à 22h. Le verrou du manoir a été ouvert avec une clé, pas forcé. La victime n'a pas opposé de résistance. J'ai manié l'arme pour vérifier la sécurité.", en: "I was broken down with Pembrooke at 10pm. The manor lock was opened with a key, not forced. The victim didn't resist. I handled the weapon to check security." }, isLie: true },
                { id: 'vivienne', witness: { fr: "Lady Vivienne", en: "Lady Vivienne" }, statement: { fr: "J'étais au théâtre avec des amies, puis seule au manoir. J'ai ouvert la fenêtre, il faisait froid. Mon mari et moi avions une relation basée sur l'argent, pas l'amour.", en: "I was at the theatre with friends, then alone at the manor. I opened the window, it was cold. My husband and I had a relationship based on money, not love." }, isLie: true },
                { id: 'pembrooke', witness: { fr: "Julian Pembrooke", en: "Julian Pembrooke" }, statement: { fr: "Ma voiture est tombée en panne, Hale m'a rejoint à 22h. J'étais venu pour un rendez-vous, pas pour voler. Personne d'autre n'est passé.", en: "My car broke down, Hale joined me at 10pm. I came for a meeting, not to steal. No one else passed by." }, isLie: true },
                { id: 'blackwood', witness: { fr: "Rupert Blackwood", en: "Rupert Blackwood" }, statement: { fr: "J'ai eu rendez-vous avec le Duc à 19h, il voulait retirer des fonds. Je suis parti vers 20h, Silas m'a vu passer au portail. Le testament m'importe peu.", en: "I had a meeting with the Duke at 7pm, he wanted to withdraw funds. I left around 8pm, Silas saw me pass the gate. The will matters little to me." }, isLie: false },
                { id: 'silas', witness: { fr: "Silas Crane", en: "Silas Crane" }, statement: { fr: "J'ai vu un rôdeur à 22h près du pavillon, montre en or, nerveux. Et j'ai vu Blackwood passer à 20h, le notaire a toujours été réglo.", en: "I saw a prowler at 10pm near the pavilion, gold watch, nervous. And I saw Blackwood pass at 8pm, the notary has always been straight." }, isLie: false },
                { id: 'krane', witness: { fr: "Victor Krane", en: "Victor Krane" }, statement: { fr: "Pour qui paye. Cette nuit-là, j'étais seul dans le bureau du Duc. Les clochards racontent n'importe quoi, surtout ce Silas.", en: "For whoever pays. That night, I was alone in the Duke's office. The homeless make up anything, especially that Silas." }, isLie: true }
            ] }},
            { decor: 'headquarters', npc: 'detective-partner', text: { fr: "Votre partenaire conclut : « Le réseau s'est refermé. Tous mentionnent le coffre, mais personne ne sait pourquoi leur ADN est sur l'arme. La vérité se cache derrière une cachette... »", en: "Your partner concludes: \"The network has closed. Everyone mentions the safe, but no one knows why their DNA is on the weapon. The truth lies behind a hiding place...\"" } }
        ]
    });


    /* ===== ACTE 2, Phase 4 : DÉDUCTION DU PARTENAIRE ===== */
    PHASES.push({
        id: 'act2_4',
        label: { fr: 'Déduction', en: 'Deduction' },
        act: 'Acte 2',
        type: 'dialogue',
        music: 'reflexion',
        pages: [
            { decor: 'headquarters', npc: 'detective-partner', text: { fr: "De retour dans la voiture banalisée, les essuie-glaces battent un rythme lancinant. Votre partenaire frappe le volant du plat de la main.\n\n« Bon sang, mais c'est bien sûr ! Tous les suspects ont mentionné, d'une manière ou d'une autre, ce fichu coffre-fort. Et regardez cette montre gousset trouvée sur la victime : l'aiguille est bloquée sur une combinaison numérique précise. Ce n'est pas l'heure de sa mort... c'est la combinaison du coffre ! Foncez à la scène de crime, c'est là-bas que tout se joue. »", en: "Back in the unmarked car, the wipers beat a steady rhythm. Your partner strikes the wheel with his palm.\n\n\"Damn it, of course! Every suspect mentioned that damned safe, one way or another. And look at that pocket watch found on the victim: the hand is stuck on a precise numerical combination. It's not the time of death... it's the combination to the safe! Get to the crime scene, that's where everything happens.\"" } }
        ]
    });

    /* ===== ACTE 3, Phase 1 : LE COFFRE VIDÉ + MUR DE RECONSTRUCTION ===== */
    PHASES.push({
        id: 'act3_1',
        label: { fr: 'Le Coffre vide', en: 'The Empty Safe' },
        act: 'Acte 3',
        type: 'dialogue',
        music: 'tension',
        pages: [
            { decor: 'crimeScene', npc: 'detective-partner', text: { fr: "Pénombre lugubre au manoir. Le ruban de police flotte au vent. Vous et votre partenaire vous tenez face au panneau de boiserie dissimulant le coffre-fort.\n\n« Allez, inspecteur. La combinaison de la montre... et ouvrez-moi ce coffre. »", en: "A gloomy half-light at the manor. Police tape floats in the wind. You and your partner stand before the wood panel concealing the safe.\n\n\"Go on, inspector. The watch's combination... and open me that safe.\"" } },
            { decor: 'crimeScene', text: { fr: "La combinaison grince doucement. Le coffre s'ouvre. À l'intérieur... rien. Plus aucun document. Plus aucun billet. Le coffre a été **VIDÉ**.\n\nWexford fronçant le sourcil : « C'est... impossible. Personne n'a dû pouvoir y entrer sans laisser de traces. »", en: "The combination grinds softly. The safe opens. Inside... nothing. No documents. No bills. The safe was **EMPTIED**.\n\nWexford frowns: \"It's... impossible. No one should have been able to enter without leaving traces.\"" } },
            { decor: 'crimeScene', npc: 'detective-partner', text: { fr: "Wexford se pencle vers le mur de reconstruction adjacent, un visage de plâtre couvrant une ancienne porte. « Regardez ce mur. » Il pousse un panneau latéral. Le mur **bascule** avec un grincement, révélant un **compartiment caché**.\n\nÀ l'intérieur : des contrats falsifiés, des registres de versements, et une **lettre signée Wexford**, datée de la semaine précédente.", en: "Wexford leans toward the adjacent reconstruction wall, a plaster face covering an old door. \"Look at this wall.\" He pushes a side panel. The wall **swings** with a groan, revealing a **hidden compartment**.\n\nInside: forged contracts, payment ledgers, and a **letter signed Wexford**, dated the previous week." } },
            { decor: 'crimeScene', npc: 'detective-partner', text: { fr: "Wexford pâlit : « Ces papiers... ils datent de la semaine dernière. » Mais vous savez que la pluie de la veille a lavé les empreintes du hall. Personne n'a pu franchir le seuil sans être vu.\n\n« Le coffre a été vidé avant notre arrivée. Quelqu'un connaissait la combinaison. »", en: "Wexford pales: \"Those papers... they date from last week.\" But you know the rain from the night before washed the prints from the hall. No one could have crossed the threshold unseen.\n\n\"The safe was emptied before our arrival. Someone knew the combination.\"" } }
        ]
    });

    /* ===== ACTE 3, Phase 2 : 6 BRANCHES - BATAILLE NAVALE CONTRE CHAQUE SUSPECT ===== */
    PHASES.push({
        id: 'act3_2',
        label: { fr: 'Branches', en: 'Branches' },
        act: 'Acte 3',
        type: 'dialogue',
        music: 'tension',
        pages: [
            { decor: 'headquarters', npc: 'detective-partner', text: { fr: "Au QG, votre partenaire étale les six dossiers sur la table, à côté des documents du coffre vide.\n\n« Chacun de nos suspects a une raison de vouloir le coffre. Mais le vrai secret, c'est celui qui l'a vidé. Convoquons-les un par un au parloir, et laissons la bataille navale trancher. »", en: "At headquarters, your partner spreads the six files on the table beside the empty safe's documents.\n\n\"Each of our suspects had reason to want the safe. But the real secret is who emptied it. Let's summon them one by one to the interrogation room, and let battleship settle it.\"" } },
            { decor: 'headquarters', npc: 'detective-partner', text: { fr: "Qui voulez-vous interroger en premier ? Le choix déclenche une branche unique.", en: "Who do you want to interrogate first? The choice triggers a unique branch." }, choices: [
                { label: { fr: 'Interroger le Major Hale', en: 'Interrogate Major Hale' }, id: 'protecteur', choiceKey: 'choisirSuspect' },
                { label: { fr: 'Interroger Lady Vivienne', en: 'Interrogate Lady Vivienne' }, id: 'femme-fatale', choiceKey: 'choisirSuspect' },
                { label: { fr: 'Interroger Julian Pembrooke', en: 'Interrogate Julian Pembrooke' }, id: 'seducteur', choiceKey: 'choisirSuspect' },
                { label: { fr: 'Interroger Rupert Blackwood', en: 'Interrogate Rupert Blackwood' }, id: 'suspect', choiceKey: 'choisirSuspect' },
                { label: { fr: 'Interroger Silas Crane', en: 'Interrogate Silas Crane' }, id: 'marginal', choiceKey: 'choisirSuspect' },
                { label: { fr: 'Interroger Victor Krane', en: 'Interrogate Victor Krane' }, id: 'criminel', choiceKey: 'choisirSuspect' }
            ], choiceKey: 'choisirSuspect', text: { fr: "Qui voulez-vous interroger en premier ?", en: "Who do you want to interrogate first?" } },
            { decor: 'dynamic', npc: 'dynamic', text: { fr: "Interrogatoire final. Le suspect est amené devant vous. L'heure de la vérité a sonné.", en: "Final interrogation. The suspect is brought before you. The time of truth has come." } },
            { decor: 'dynamic', npc: 'dynamic', text: { fr: "Le duel de bataille navale commence. Sur le damier, vos navires et ceux du suspect s'affrontent. Chaque coup de canon révèle un fragment de vérité.", en: "The battleship duel begins. On the grid, your ships face the suspect's. Each cannon shot reveals a fragment of truth." }, minigame: { type: 'bataille-navale', evidence: 'witness', title: { fr: 'Bataille Navale', en: 'Battleship' }, desc: { fr: "Duel tactique contre le suspect. Victoire = indice révélé. Défaite = indice caché.", en: "Tactical duel against the suspect. Victory = clue revealed. Defeat = clue hidden." }, clue: { fr: "Le suspect a perdu le contrôle : ses réactions trahissent une connaissance trouble de cette affaire.", en: "The suspect lost composure: their reactions betray troubling familiarity with this case." }, failClue: { fr: "Le suspect triomphe : il connaît trop bien les eaux de cette affaire.", en: "The suspect triumphs: they know these waters far too well." } } },
            { decor: 'headquarters', npc: 'detective-partner', text: { fr: "Wexford note les réactions : « Chacun a une version. Mais le vrai indice, c'est ce que personne n'a dit. »", en: "Wexford notes the reactions: \"Each has a version. But the real clue is what no one said.\"" } }
        ]
    });

    /* ===== ACTE 3, Phase 3 : CONFRONTATION FINALE + TWIST ===== */
    PHASES.push({
        id: 'act3_3',
        label: { fr: 'Twist Final', en: 'Final Twist' },
        act: 'Acte 3',
        type: 'dialogue',
        music: 'stress',
        pages: [
            { decor: 'headquarters', npc: 'detective-partner', text: { fr: "Au QG, le moment est venu. Votre partenaire étale les six dossiers sur la table, à côté des documents du coffre vide.\n\nVous avez interrogé un ou plusieurs suspects. Chaque victoire au duel de bataille navale a révélé un fragment de vérité. Mais le véritable secret, c'est ce que l'ensemble révèle.\n\nQui accusez-vous ? Le partenaire qui vous a guidé depuis le début... ou un des suspects ?", en: "At headquarters, the time has come. Your partner spreads the six files on the table beside the empty safe's documents.\n\nYou have interrogated one or more suspects. Each victory at the battleship duel revealed a fragment of truth. But the real secret is what it all reveals.\n\nWho do you accuse? The partner who guided you from the start... or one of the suspects?" }, choices: [
                { label: { fr: 'Accuser le Major Hale (garde du corps)', en: 'Accuse Major Hale (bodyguard)' }, id: 'protecteur', choiceKey: 'accuser' },
                { label: { fr: 'Accuser Lady Vivienne (épouse)', en: 'Accuse Lady Vivienne (wife)' }, id: 'femme-fatale', choiceKey: 'accuser' },
                { label: { fr: 'Accuser Julian Pembrooke (ami)', en: 'Accuse Julian Pembrooke (friend)' }, id: 'seducteur', choiceKey: 'accuser' },
                { label: { fr: 'Accuser Rupert Blackwood (notaire)', en: 'Accuse Rupert Blackwood (notary)' }, id: 'suspect', choiceKey: 'accuser' },
                { label: { fr: 'Accuser Silas Crane (le clochard)', en: 'Accuse Silas Crane (the homeless man)' }, id: 'marginal', choiceKey: 'accuser' },
                { label: { fr: 'Accuser Victor Krane (homme de main)', en: 'Accuse Victor Krane (the hired hand)' }, id: 'criminel', choiceKey: 'accuser' },
                { label: { fr: 'Accuser Wexford (le partenaire)', en: 'Accuse Wexford (the partner)' }, id: 'detective', choiceKey: 'accuser' }
            ], choiceKey: 'accuser', text: { fr: "Qui accusez-vous ?", en: "Who do you accuse?" } }
        ]
    });

    /* ===== OUTRO - ÉPILOGUE ===== */
    PHASES.push({
        id: 'outro',
        label: { fr: 'Épilogue', en: 'Epilogue' },
        act: 'Outro',
        type: 'outro',
        music: 'theme',
        pages: [
            { decor: 'headquarters', npc: 'detective-partner', text: { fr: "L'affaire est classée. Le vrai coupable croupit en prison. Le coffre-fort vide a révélé le plus grand secret : celui qui orchestre depuis l'ombre.", en: "Case closed. The true culprit is in prison. The emptied safe revealed the greatest secret: the one who orchestrated from the shadows." } },
            { decor: 'universe', text: { fr: "La ville murmure à nouveau sous la pluie. Une autre affaire vous attend, mais celle-ci est résolue.", en: "The city whispers again under the rain. Another case awaits you, but this one is solved." } },
            { decor: 'universe', text: { fr: "FIN - True Detective.", en: "END - True Detective." } }
        ]
    });

    /* ===== OUTRO - ÉPILOGUE ===== */
    PHASES.push({
        id: 'outro',
        label: { fr: 'Épilogue', en: 'Epilogue' },
        act: 'Outro',
        type: 'outro',
        music: 'theme',
        pages: [
            { decor: 'headquarters', npc: 'detective-partner', text: { fr: "L'affaire est classée. Le vrai coupable croupit en prison, le mobile était l'argent, la méthode, la trahison.", en: "Case closed. The real culprit is in prison, the motive was money, the method, betrayal." } },
            { decor: 'universe', text: { fr: "La ville murmure à nouveau sous la pluie. Une autre affaire vous attend, mais celle-ci est résolue.", en: "The city whispers again under the rain. Another case awaits you, but this one is solved." } },
            { decor: 'universe', text: { fr: "FIN - True Detective.", en: "END - True Detective." } }
        ]
    });

    global.TDPhases = PHASES;

})(typeof globalThis !== 'undefined' ? globalThis : this);