// Patch app.js : ajoute renderEvidenceBeam + modifie scrShowAdvance
const fs = require('fs');
const path = require('path');
const file = path.join(__dirname, '..', 'true-detective', 'app.js');
let c = fs.readFileSync(file, 'utf8');

const old = "    function scrShowAdvance(page) {\r\n        if (page.choiceKey) {\r\n            var choices = page.choices || [];\r\n            scr.awaitingChoice = true;\r\n            $.choicesContainer.innerHTML = '';\r\n            choices.forEach(function (choiceId) {\r\n                var btn = document.createElement('button');\r\n                btn.className = 'btn btn-choice';\r\n                btn.textContent = scrChoiceLabel(choiceId);\r\n                btn.addEventListener('click', function () {\r\n                    if (!scr.awaitingChoice) return;\r\n                    scr.awaitingChoice = false;\r\n                    scrApplyChoice(page.choiceKey, choiceId);\r\n                });\r\n                $.choicesContainer.appendChild(btn);\r\n            });\r\n        } else {\r\n            $.continueBtn.classList.remove('hidden');\r\n            $.continueBtn.textContent = getText('continue') || 'Continuer';\r\n            $.continueBtn.onclick = function () { scrNext(); };\r\n        }\r\n    }";

const newF = "    function renderEvidenceBeam(summary) {\r\n        if (!summary) return;\r\n        var s = scrGetState();\r\n        var ev = s.evidence || {};\r\n        var cats = [\r\n            ['alibi', 'Alibi'], ['mobile', 'Mobile'], ['opportunity', 'Opportunit\u00e9'],\r\n            ['forensic', 'Scientifique'], ['witness', 'T\u00e9moins'], ['timeline', 'Chronologie']\r\n        ];\r\n        var html = '<div class=\"evidence-beam\">';\r\n        html += '<div class=\"evidence-beam-title\">FAISCEAU DE PREUVES \\u2014 ' + summary.score + '/' + summary.max + ' indices rassembl\\u00e9s</div>';\r\n        cats.forEach(function (cc) {\r\n            var val = ev[cc[0]] || 0;\r\n            var pct = Math.round((val / 3) * 100);\r\n            html += '<div class=\"evidence-row\">';\r\n            html += '<span class=\"evidence-label\">' + cc[1] + '</span>';\r\n            html += '<span class=\"evidence-track\"><span class=\"evidence-fill ' + (val > 0 ? 'active' : '') + '\" style=\"width:' + pct + '%\"></span></span>';\r\n            html += '<span class=\"evidence-count\">' + val + '/3</span>';\r\n            html += '</div>';\r\n        });\r\n        html += '</div>';\r\n        var div = document.createElement('div');\r\n        div.innerHTML = html;\r\n        $.choicesContainer.appendChild(div);\r\n    }\r\n\r\n    function scrShowAdvance(page) {\r\n        if (page.evidenceSummary) {\r\n            renderEvidenceBeam(page.evidenceSummary);\r\n            $.continueBtn.classList.remove('hidden');\r\n            $.continueBtn.textContent = getText('continue') || 'Continuer';\r\n            $.continueBtn.onclick = function () { scrNext(); };\r\n            return;\r\n        }\r\n        if (page.choiceKey) {\r\n            var choices = page.choices || [];\r\n            scr.awaitingChoice = true;\r\n            $.choicesContainer.innerHTML = '';\r\n            choices.forEach(function (choiceId) {\r\n                var btn = document.createElement('button');\r\n                btn.className = 'btn btn-choice';\r\n                btn.textContent = scrChoiceLabel(choiceId);\r\n                btn.addEventListener('click', function () {\r\n                    if (!scr.awaitingChoice) return;\r\n                    scr.awaitingChoice = false;\r\n                    scrApplyChoice(page.choiceKey, choiceId);\r\n                });\r\n                $.choicesContainer.appendChild(btn);\r\n            });\r\n        } else {\r\n            $.continueBtn.classList.remove('hidden');\r\n            $.continueBtn.textContent = getText('continue') || 'Continuer';\r\n            $.continueBtn.onclick = function () { scrNext(); };\r\n        }\r\n    }";

if (c.indexOf(old) === -1) {
    console.log('ERREUR: bloc old introuvable');
    process.exit(1);
}
c = c.replace(old, newF);
fs.writeFileSync(file, c, 'utf8');
console.log('OK: app.js patch\u00e9');
